/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface CashflowPoolInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "accRewardPerShare"
      | "businessAddress"
      | "cashflowToken"
      | "claimYield"
      | "claimedDistributions"
      | "depositRevenue"
      | "fundDeadline"
      | "fundingRaised"
      | "fundingTarget"
      | "invest"
      | "isFunded"
      | "oracleAddress"
      | "owner"
      | "renounceOwnership"
      | "revenueSharePercentage"
      | "rewardDebt"
      | "stablecoin"
      | "totalRevenueDeposited"
      | "transferOwnership"
      | "withdrawRaisedFunds"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "FundsWithdrawnByBusiness"
      | "InvestmentMade"
      | "OwnershipTransferred"
      | "RevenueDeposited"
      | "YieldClaimed"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "accRewardPerShare",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "businessAddress",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "cashflowToken",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimYield",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "claimedDistributions",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "depositRevenue",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "fundDeadline",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundingRaised",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "fundingTarget",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "invest",
    values: [BigNumberish]
  ): string;
  encodeFunctionData(functionFragment: "isFunded", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "oracleAddress",
    values?: undefined
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "revenueSharePercentage",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "rewardDebt",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "stablecoin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "totalRevenueDeposited",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;
  encodeFunctionData(
    functionFragment: "withdrawRaisedFunds",
    values?: undefined
  ): string;

  decodeFunctionResult(
    functionFragment: "accRewardPerShare",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "businessAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "cashflowToken",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "claimYield", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "claimedDistributions",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "depositRevenue",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundDeadline",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingRaised",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "fundingTarget",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "invest", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "isFunded", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "oracleAddress",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "revenueSharePercentage",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "rewardDebt", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "stablecoin", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "totalRevenueDeposited",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "withdrawRaisedFunds",
    data: BytesLike
  ): Result;
}

export namespace FundsWithdrawnByBusinessEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace InvestmentMadeEvent {
  export type InputTuple = [investor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [investor: string, amount: bigint];
  export interface OutputObject {
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace RevenueDepositedEvent {
  export type InputTuple = [amount: BigNumberish];
  export type OutputTuple = [amount: bigint];
  export interface OutputObject {
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace YieldClaimedEvent {
  export type InputTuple = [investor: AddressLike, amount: BigNumberish];
  export type OutputTuple = [investor: string, amount: bigint];
  export interface OutputObject {
    investor: string;
    amount: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CashflowPool extends BaseContract {
  connect(runner?: ContractRunner | null): CashflowPool;
  waitForDeployment(): Promise<this>;

  interface: CashflowPoolInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  accRewardPerShare: TypedContractMethod<[], [bigint], "view">;

  businessAddress: TypedContractMethod<[], [string], "view">;

  cashflowToken: TypedContractMethod<[], [string], "view">;

  claimYield: TypedContractMethod<[], [void], "nonpayable">;

  claimedDistributions: TypedContractMethod<
    [arg0: AddressLike],
    [bigint],
    "view"
  >;

  depositRevenue: TypedContractMethod<
    [amount: BigNumberish],
    [void],
    "nonpayable"
  >;

  fundDeadline: TypedContractMethod<[], [bigint], "view">;

  fundingRaised: TypedContractMethod<[], [bigint], "view">;

  fundingTarget: TypedContractMethod<[], [bigint], "view">;

  invest: TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;

  isFunded: TypedContractMethod<[], [boolean], "view">;

  oracleAddress: TypedContractMethod<[], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  revenueSharePercentage: TypedContractMethod<[], [bigint], "view">;

  rewardDebt: TypedContractMethod<[arg0: AddressLike], [bigint], "view">;

  stablecoin: TypedContractMethod<[], [string], "view">;

  totalRevenueDeposited: TypedContractMethod<[], [bigint], "view">;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  withdrawRaisedFunds: TypedContractMethod<[], [void], "nonpayable">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "accRewardPerShare"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "businessAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "cashflowToken"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "claimYield"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "claimedDistributions"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "depositRevenue"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "fundDeadline"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundingRaised"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "fundingTarget"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "invest"
  ): TypedContractMethod<[amount: BigNumberish], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "isFunded"
  ): TypedContractMethod<[], [boolean], "view">;
  getFunction(
    nameOrSignature: "oracleAddress"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "revenueSharePercentage"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "rewardDebt"
  ): TypedContractMethod<[arg0: AddressLike], [bigint], "view">;
  getFunction(
    nameOrSignature: "stablecoin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "totalRevenueDeposited"
  ): TypedContractMethod<[], [bigint], "view">;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "withdrawRaisedFunds"
  ): TypedContractMethod<[], [void], "nonpayable">;

  getEvent(
    key: "FundsWithdrawnByBusiness"
  ): TypedContractEvent<
    FundsWithdrawnByBusinessEvent.InputTuple,
    FundsWithdrawnByBusinessEvent.OutputTuple,
    FundsWithdrawnByBusinessEvent.OutputObject
  >;
  getEvent(
    key: "InvestmentMade"
  ): TypedContractEvent<
    InvestmentMadeEvent.InputTuple,
    InvestmentMadeEvent.OutputTuple,
    InvestmentMadeEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;
  getEvent(
    key: "RevenueDeposited"
  ): TypedContractEvent<
    RevenueDepositedEvent.InputTuple,
    RevenueDepositedEvent.OutputTuple,
    RevenueDepositedEvent.OutputObject
  >;
  getEvent(
    key: "YieldClaimed"
  ): TypedContractEvent<
    YieldClaimedEvent.InputTuple,
    YieldClaimedEvent.OutputTuple,
    YieldClaimedEvent.OutputObject
  >;

  filters: {
    "FundsWithdrawnByBusiness(uint256)": TypedContractEvent<
      FundsWithdrawnByBusinessEvent.InputTuple,
      FundsWithdrawnByBusinessEvent.OutputTuple,
      FundsWithdrawnByBusinessEvent.OutputObject
    >;
    FundsWithdrawnByBusiness: TypedContractEvent<
      FundsWithdrawnByBusinessEvent.InputTuple,
      FundsWithdrawnByBusinessEvent.OutputTuple,
      FundsWithdrawnByBusinessEvent.OutputObject
    >;

    "InvestmentMade(address,uint256)": TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;
    InvestmentMade: TypedContractEvent<
      InvestmentMadeEvent.InputTuple,
      InvestmentMadeEvent.OutputTuple,
      InvestmentMadeEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;

    "RevenueDeposited(uint256)": TypedContractEvent<
      RevenueDepositedEvent.InputTuple,
      RevenueDepositedEvent.OutputTuple,
      RevenueDepositedEvent.OutputObject
    >;
    RevenueDeposited: TypedContractEvent<
      RevenueDepositedEvent.InputTuple,
      RevenueDepositedEvent.OutputTuple,
      RevenueDepositedEvent.OutputObject
    >;

    "YieldClaimed(address,uint256)": TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
    YieldClaimed: TypedContractEvent<
      YieldClaimedEvent.InputTuple,
      YieldClaimedEvent.OutputTuple,
      YieldClaimedEvent.OutputObject
    >;
  };
}
